#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check workspace before pushing
npx nx format:check
npx nx affected --target=lint,test,build --parallel=3

# Check CDK setup before pushing
alias cdk="npm --prefix cdk"
cdk ci
cdk run lint
cdk run test
