import { InMemoryDraftStorage } from '@newsletters-nx/newsletters-data-client';

export const makeInMemoryStorageInstance = () =>
	new InMemoryDraftStorage([
		{
			identityName: 'avon-recumbent',
			name: 'Avon Recumbent',
			category: 'article-based',
			signUpDescription:
				'Quod nobis aperiam aperiam ipsum nobis officiis explicabo molestias quibusdam.',
			frequency: 'Weekly',
			status: 'paused',
			restricted: false,
			emailConfirmation: false,
			brazeNewsletterName: 'Editorial_AvonRecumbentUs',
			brazeSubscribeAttributeName: 'AvonRecumbentUs_Subscribe_Email',
			brazeSubscribeEventNamePrefix: 'avon_recumbent_US',
			signUpEmbedDescription: "We'll send you Avon Recumbent weekly",
			theme: 'culture',
			group: 'Work',
			regionFocus: 'UK',
			listId: 5770,
			exampleUrl: '/world/series/series-avon-recumbent/latest/email',
			signupPage:
				'/global/sign-up-for-the-avon-recumbent-newsletter-our-free-email',
			campaignName: 'AvonRecumbentUs',
			campaignCode: 'avonrecumbentUS_email',
			brazeSubscribeAttributeNameAlternate: [
				'email_subscribe_avon_recumbent_US',
			],
			creationTimeStamp: 1633539258449,
			figmaIncludesThrashers: false,
			launchDate: new Date('1970-01-02T00:21:18.876Z'),
			signUpPageDate: new Date('1970-01-02T00:21:18.876Z'),
			thrasherDate: new Date('1970-01-02T00:21:18.876Z'),
			privateUntilLaunch: false,
			onlineArticle: 'Web for all sends',
		},

		{
			listId: 7000,
			name: 'Test draft newsletter',
			category: 'article-based',
			identityName: 'test-draft-newsletter',
			brazeSubscribeEventNamePrefix: 'test_draft_newsletter',
			brazeNewsletterName: 'Editorial_Testdraftnewsletter',
			brazeSubscribeAttributeName: 'Testdraftnewsletter_Subscribe_Email',
			brazeSubscribeAttributeNameAlternate: [
				'email_subscribe_test_draft_newsletter',
			],
			campaignName: 'Testdraftnewsletter',
			campaignCode: 'testdraftnewsletter_email',
			creationTimeStamp: 1633539258449,
		},
		{
			listId: 7001,
			name: 'Other Test draft newsletter',
			identityName: 'other-test-draft-newsletter',
			category: 'other',
			brazeSubscribeEventNamePrefix: 'other_test_draft_newsletter',
			brazeNewsletterName: 'Editorial_Othertestdraftnewsletter',
			brazeSubscribeAttributeName: 'Othertestdraftnewsletter_Subscribe_Email',
			brazeSubscribeAttributeNameAlternate: [
				'email_subscribe_other_test_draft_newsletter',
			],
			campaignName: 'Othertestdraftnewsletter',
			campaignCode: 'othertestdraftnewsletter_email',
			theme: 'news',
			creationTimeStamp: 1633539258449,
		},
		{
			name: 'Response Academic',
			identityName: 'response-academic',
			category: 'article-based-legacy',
			brazeSubscribeEventNamePrefix: 'response_academic',
			brazeNewsletterName: 'Editorial_ResponseAcademic',
			brazeSubscribeAttributeName: 'ResponseAcademic_Subscribe_Email',
			brazeSubscribeAttributeNameAlternate: [
				'email_subscribe_response_academic',
			],
			campaignName: 'ResponseAcademic',
			campaignCode: 'responseacademic_email',
			listId: 7002,
			theme: 'lifestyle',
			signUpDescription:
				'Officia neque totam temporibus incidunt ad dolorem quo sit mollitia.\\net molestiae reprehenderit.\\nquo dolores beatae suscipit veniam maiores delectus.',
			creationTimeStamp: 1633539258449,
		},
		{
			identityName: 'wagon-automotive',
			name: 'Wagon Automotive',
			signUpDescription: 'Mollitia saepe odio',
			category: 'article-based',
			frequency: 'Weekly',
			brazeNewsletterName: 'Editorial_WagonAutomotiveAu',
			brazeSubscribeAttributeName: 'WagonAutomotiveAu_Subscribe_Email',
			brazeSubscribeEventNamePrefix: 'wagon_automotive_AU',
			theme: 'news',
			group: 'Work',
			listId: 7009,
			creationTimeStamp: 1633539258449,
		},
		{
			identityName: 'background-hatchback',
			name: 'Background Hatchback',
			category: 'fronts-based',
			signUpDescription:
				'Veritatis ipsum asperiores optio sunt eum ab architecto.',
			frequency: 'Weekly',
			brazeNewsletterName: 'Editorial_BackgroundHatchbackUk',
			brazeSubscribeAttributeName: 'BackgroundHatchbackUk_Subscribe_Email',
			brazeSubscribeEventNamePrefix: 'background_hatchback_UK',
			theme: 'news',
			group: 'Opinion',
			listId: 7010,
			regionFocus: 'UK',
			creationTimeStamp: 1633539258449,
			launchDate: new Date('1970-01-02T00:21:18.876Z'),
			signUpPageDate: new Date('1970-01-02T00:21:18.876Z'),
			thrasherDate: new Date('1970-01-02T00:21:18.876Z'),
		},
	]);
