name: Snyk
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  security:
    with:
      ORG: guardian
      SKIP_SBT: true # SBT is not used in this project
      EXCLUDE: project.json
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
